### PR TITLE
Added "ci_drawable_unselected" param to set different background for unselected indicator

### PR DESCRIPTION
**Pull request by polok**

### CODE REVIEW

**Comment by icastell** [comment]
Great! Please, could you push a version with this feature in the actual maven repo? I'm going to launch a new version of my app and I would like to include this feature. Or, when are you planning next release of the library?

Thx!

**Comment by ongakuer** [comment]
@icastell  Ok, I will push it today.

**Comment by icastell** [comment]
@ongakuer  Perfect! Thank you so much!

**Comment by zoumy** [comment]
@ongakuer I uesed 'me.relex:circleindicator:1.0.0@aar'
Error:(17) No resource identifier found for attribute 'ci_drawable_unselecte' in package 'activity.android.mobile.alipay.com.anthome'

**Comment by ongakuer** [comment]
@zoumy  Sorry,  "ci_drawable_unselecte" param is not support for version 1.0.0

**Pull request merged**
