### PR TITLE
Added feature/bugfix for CircleIndicator in CoordinatorLayout

### PR DESCRIPTION
**Pull request by daniellAlgar**
SnackBar used to hide the indicator. Now the indicator gets pushed up by the snackbar (as the typical FAB behaviour).

### CODE REVIEW

**Comment by daniellAlgar** [comment]
@ongakuer Any feedback on the pull request maybe?

**Comment by ongakuer** [comment]
@daniellAlgar Sorry, I forgot. Can you add some samples ?

**Comment by daniellAlgar** [comment]
If I haven't made a git-mistake there should now be a new sample option **With SnackBar in CoordinatorLayout** that shows the behaviour of the Circle Indicator when a SnackBar is being shown. (i.e. the CircleIndicator should be translated in Y as to not be covered by the SnackBar). 

Also, I reverted changes I originally made to the CircleIndicator build.gradle. I had upped the versions to the latest (24) but I think that should be a separate pull request.

**Comment by ongakuer** [comment]
Thanks For Your Pull Request. 
I renamed Behavior class and removed ```@CoordinatorLayout.DefaultBehavior``` Annotation

If this library supports DefaultBehavior, we have to import design support Library.  There will be unfriendly to others.

**Pull request merged**
