### PR TITLE
Add support for RecyclerView with PagerSnapHelper

### PR DESCRIPTION
**Pull request by anasanasanas**
Add support for RecyclerView with  PagerSnapHelper
https://developer.android.com/reference/android/support/v7/widget/PagerSnapHelper

### CODE REVIEW

**Comment by ongakuer** [comment]
Thanks for your good works.  I think it's better to create a new class for RecyclerView

**Comment by anasanasanas** [comment]
Hello @ongakuer,
do you mean creating a new CircleIndicator class for the RecyclerView support?

**Comment by ongakuer** [comment]
Yes

**Comment by ongakuer** [comment]
3f3b73f1cc39a0b0ce0a76e11dcaed67e27f4a42

**Comment by anasanasanas** [comment]
Good job.
Thanks ongakuer.

**Pull request closed without merging**
